runtime:
  cache_dir: ./.cache/antora
site:
  title: FaaS Tutorial Docs
  url: https://redhat-developer-demos.github.io/faas-tutorial/
  start_page: faas-tutorial::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: documentation
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./docs
