= Getting Started - Nodejs
include::_attributes.adoc[]

[#overview]
== Overview 

This section shows how to build and deploy an simple greeter nodejs application as Knative service 

[#create-nodejs-service]
== Create Service

=== Create app directory
[source,bash]
----
mkdir -p $PROJECT_HOME/build/getstarted/nodejs
----

=== Create package.json
[source,json]
----
include::{examplesdir}/getstarted/nodejs/package.json.txt[]
----

=== Create Application
[source,javascript]
----
include::{examplesdir}/getstarted/nodejs/app.js.txt[]
---- 

=== Create a Dockerfile
[source,dockerfile]
----
include::{examplesdir}/getstarted/nodejs/Dockerfile.txt[]
---- 

[#build-nodejs-service]
== Build Service

From $PROJECT_HOME/build/getstarted/nodejs:

[source,json]
----
docker build --rm -t dev.local/greeter-nodejs:1.0.0 .
----

[#deploy-nodejs-service]
== Deploy Service

To deploy the Knative service we need to create file called `service.yaml` in `$PROJECT_HOME/build/getstarted/nodejs` with the following content:

=== Create service.yaml
[source,yaml]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/greeter-nodejs:1.0.0 #<1>
----

<1> It is very important that the image is a fully qualified name docker image name with tag.

[#invoke-nodejs-service]
== Invoke Service

The applications can be invoked only using `knative-ingress-gateway` which was deployed with Knative serving deployment.

 The following snippet shows how to invoke the greeter nodejs service that was deployed earlier:

[source,bash]
----
export IP_ADDRESS=$(kubectl get node -o 'jsonpath={.items[0].status.addresses[0].address}')

export SERVICE_NODEPORT=$(oc get svc knative-ingressgateway -n istio-system -o 'jsonpath={.spec.ports[?(@.port==80)].nodePort}')

export HOST_URL=$(kubectl get routes.serving.knative.dev greeter  -o jsonpath='{.status.domain}')

curl -H "Host: ${HOST_URL}" ${IP_ADDRESS}:${SERVICE_NODEPORT}
----