= Getting Started
include::_attributes.adoc[]

[#overview]
== Overview
The getting started allows you to deploy Knative services using https://github.com/knative/serving[Knative Serving].  This tutorial shows example of deploying a simple Greeter service in following languages,

- Java
- Nodejs

While deploying application in different languages demonstrates the polyglot capabilities as well as some key Knative concepts.

NOTE: All the code snippets shown in these sections are available in {repo-url}/solutions/getstarted[Solutions] folder.

[#environment]
== Environment

Its assumed that you have setup the minishift and deployed Knative serving.  If not please vist xref:1setup.adoc[setup] section to do the same before proceeding further.

[#configure-cli]
=== Configure the CLI

Before we go further with the build its necessary that we configure the command line to interact with Docker Daemon of the minishift and we use the right compatible version of the OpenShift CLI.

[source,bash]
----
eval $(minishift docker-env) && eval $(minishift oc-env)
----

[#sources]
== Sources

Clone the sources from {repo-url}

[source,bash]
----
git clone {repo-url}
----

For the rest of the document we call the cloned folder as `$PROJECT_HOME`.


[#build-services]

== Build Services

Build the greeter service in the language of your choice,

** xref:2.2get_started_java.adoc[Java Service]
** xref:2.1get_started_nodejs.adoc[Nodejs Service]

[#deploy-service]
== Deploy Service

Navigate to solutions/getstarted folder of the `$PROJECT_HOME`. 

=== service.yaml
[source,yaml]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/greeter:0.0.1 #<1>
----

<1> It is very important that the image is a fully qualified name docker image name with tag.

include::{partialsdir}/deploy_service.adoc[tag=svcdefault]

After successful deployment of the service we should see a Kubernetes deployment called `greeter-00001-deployment` available in the OpenShift dashboard:

include::{partialsdir}/deployments.adoc[tag=greeter-00001]


[#invoke-service]
== Invoke Service

include::{partialsdir}/invoke_service.adoc[tag=invokedefault]
