= Getting Started
include::_attributes.adoc[]

[#overview]
== Overview
The getting started allows you to deploy Knative services using https://github.com/knative/serving[Knative Serving].  This tutorial shows example of deploying a simple Greeter service in following languages,

- Nodejs
- Java

While deploying application in different languages demonstrates the polyglot capabilities as well as some key Knative concepts.

The completed solutions is available in the {repo-url}/solutions/getstarted[Solutions] folder.

[#environment]
== Environment

Its assumed that you have setup the minishift and deployed Knative serving.  If not please vist xref:1setup.adoc[setup] section to do the same before proceeding further.

[#configure-cli]
=== Configure the CLI

Before we go further with the build its necessary that we configure the command line to interact with Docker Daemon of the minishift and we use the right compatible version of the OpenShift CLI.

[source,bash]
----
eval $(minishift docker-env) && eval $(minishift oc-env)
----

[#sources]
== Sources

Clone the sources from {repo-url}

[source,bash]
----
git clone {repo-url}
----

For the rest of the document we call the cloned folder as `$PROJECT_HOME`.

Create a directory under $PROJECT_HOME called **build**, you will be using this directory as your working directory. 

[source,bash]
----
mkdir -p $PROJECT_HOME/build
----

You can always refer to the {repo-url}/solutions/getstarted[Solutions] if you need help.

[#deploy-services]
== Deploy Services
** xref:2.1get_started_nodejs.adoc[Nodejs Service]
** xref:2.2get_started_java.adoc[Java Service]

[#points-to-ponder]
== Points to Ponder

After you have deployed the Java service, you would have noticed that it has triggered a new Kubernetes deployment something like `greeter-00002-deployment`.  Wondering the reason for it, lets compare the two `service.yaml` that were deployed:

.Greeter Service
|====
| **NodeJs** service | **Java** service 
a|
[source,yaml]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/greeter:1.0.0
----
a|
[source,yaml]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/greeter:2.0.0 
----
|====

If you observe the only diffrence between the two service deployments is the version of the Docker Image, which is a configuration change.  Knative follows https://12factor.net/[12-factor] application principles where in every configuration change leads to a new revision,

[source,bash]
----
kubectl get configurations.serving.knative.dev #<1>
kubectl get revisions.serving.knative.dev #<2>
----

<1> Will return only one configuration called `greeter`
<2> Will return two revisions something like `greeter-00001` and `greeter-00002`

[NOTE]
====
Each revision will trigger new deployments, and since the service is configured with **runLatest** it always serves the latest revision.  Check xref:3.revisions_configurations[Revisions and Configurations] for more details on revisions, configurations and other possible revision rollout strategy.
====