= Revisions and Configurations
include::_attributes.adoc[]

== Overview 

Knative follows https://12factor.net/[12-factor] application principles where in every configuration change leads to a new revision.  The configuration change could be image change, environment variables gets added or removed from the configuration.

[source,bash]
----
kubectl get configurations.serving.knative.dev #<1>
kubectl get revisions.serving.knative.dev #<2>
----

<1> Will return only one configuration called `greeter`
<2> Will return two revisions something like `greeter-00001` and `greeter-00002`

[#rollout-changes]
== Rolling out changes

In the previous service deployments we did update the image from NodeJS to Java, now lets add a new environment variable(s) to the configuration and we will observe that it triggers new revision and deployment :

=== Adding Environment variable

[source,bash]
----
cd $PROJECT_HOME/build/getstarted/java
----

Create a new `service-env.yaml` in `$PROJECT_HOME/build/getstarted/java` with the following content:
[source,yaml]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            env:
              - name: MESSAGE # <1>
                value: Hello World
            image: dev.local/greeter:2.0.0

----

<1> Updating the configuration with a environment variable called "MESSAGE"

The GreeterController.java is already setup to use the `MESSAGE` variable via `@Value` annotation:

[source,java]
----
include::{examplesdir}/getstarted/java/GreeterController.java.txt[]
---- 

include::{partialsdir}/deploy_service.adoc[tag=svcenv]

The service deployment should now trigger a new revision something like `greeter-00003` and a new deployment for the revision named `greeter-00003-deployment` and it will available in the OpenShift dashboard:

include::{partialsdir}/deployments.adoc[tag=greeter-00003]

<<invoke-rev-service,Invoking Service>> should return a response like **Java::Hello World** instead of the earlier **Java::Knative on OpenShift**


[#rollback-changes]
== Rolling back changes

To Rollback Changes we can could always delete the application and redeploy the previous version.  As Knative is backed by Istio we could still have the newer deployment in but without routing traffic to it.

Knative allows us to do this using a strategy called "Pinned Revisions" 

=== Applying Pinned Revision

Create a new `service-pinned.yaml` in `$PROJECT_HOME/build/java` with the following content:
[source,yaml]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  pinned:
    revisionName: greeter-00001 #<1>
    configuration:
      revisionTemplate:
        spec:
          container:
            env:
              - name: MESSAGE
                value: Hello World
            image: dev.local/greeter:2.0.0

----

<1> In this case we are setting it to existing revision called `greeter-00001`

[TIP]
====
You can set `revisionName` to any available revision. You can find all the available revisions using the command:
[source,bash]
----
kubectl get revisions.serving.knative.dev 
----
====

include::{partialsdir}/deploy_service.adoc[tag=svcpinned]

Though a new revision `greeting-00003` has been created with previous deployment, with this **pinned** revision rollout strategy we are pinning the service to use revision `greeting-00001`.

[IMPORTANT]
====
For pinned revision service deployments the configuration section of the `service.yaml` is completely ignored. But since its a mandatory element of the service schema we leave it in tact with last revision to avoid creation of new revision with the pinned revision service deployment.
====

[#invoke-rev-service]
== Invoke Service

include::{partialsdir}/invoke_service.adoc[]

The curl command above should return a response like **NodeJs::Knative on OpenShift** instead of **Java::Hello World**