= Introduction to Knative
include::_attributes.adoc[]

WARNING: This tutorial is under development and some sections can undergo rapid changes. 

This tutorial allows you to get started with https://cloud.google.com/knative/[Knative].  The tutorial is divided into the following sections:

xref:1setup.adoc[Setup] 

This section details on setting up Knative on https://docs.okd.io/latest/minishift/getting-started/installing.html[minishift] starting from minishift profile setup to deploying Knative components such as https://github.com/knative/docs/tree/master/serving[Serving], https://github.com/knative/docs/tree/master/eventing[Eventing].

xref:2get_started.adoc[Get Started]

This section details how to deploy your services using https://github.com/knative/docs/tree/master/serving[Serving] along with explaining the workflow thats involved with each service deployment using the primary building block called https://github.com/knative/serving/blob/master/docs/spec/spec.md#service[Service]

xref:3.revisions_configurations.adoc[Revisions and Configurations]

This section extends the previous section in going a bit deeper into the other building blocks of  https://github.com/knative/docs/tree/master/serving[Serving] namely https://github.com/knative/serving/blob/master/docs/spec/spec.md#revision[Revisions] and https://github.com/knative/serving/blob/master/docs/spec/spec.md#configuration[Configurations].

xref:4.eventing.adoc[Eventing]

This section introduces you to another important component of Knative the https://github.com/knative/eventing[Eventing].  Eventing allows us to build a network services using events, in which the service can listen to Events via Event Sources.  The section only covers the very basic of https://github.com/knative/eventing[Eventing].

xref:5.traffic_splitting.adoc[Traffic Splitting]

This last section goes deeper into another important building block of https://github.com/knative/docs/tree/master/serving[Serving] namely https://github.com/knative/serving/blob/master/docs/spec/spec.md#route[Route].  In this section we will see how to do smart routing between various https://github.com/knative/serving/blob/master/docs/spec/spec.md#revision[Revisions] of the service.