apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: myService
spec:
    pinned:
      revisionName: ${2,revisionName}
    configuration:
      revisionTemplate:
        spec:
          container:
            image: serviceContainerImage